name: Dependency Review

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  analyze:
    name: Analyze Dependencies
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b  # v3.0.2

      # Uncomment this after merge of DEVOPS-93
      #   - name: Scan actions used in this repository
      #     uses: ed-fi-alliance-oss/ed-fi-actions/.github/workflows/repository-scanner.yml@latest

      - name: Dependency Review ("Dependabot on PR")
        uses: actions/dependency-review-action@a9c83d3af6b9031e20feba03b904645bb23d1dab  # v1.0.2
