name: Download packages and create installation scripts

on:
    workflow_dispatch:
        inputs:
            target_environment:
                description: "Select the environment"
                required: true
                type: choice
                options:
                    - develop
                default: staging
            resource_group:
                description: "The resource group of the VM"
                required: true
            web_api_vm_name:
                description: "The name of the WEB API VM"
                required: true
            sql_vm_name:
                description: "The name of the SQL VM"
                required: true
            version:
                description: "The version of EdFi.Suite3.Installer.WebApi to install"
                required: true
                default: "7.2.4"
            db_server:
                description: "Database server IP address"
                required: true
            db_username:
                description: "Database username"
                required: true
            db_password:
                description: "Database password"
                required: true


env:
    ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}

jobs:
    run-command:
        runs-on: ubuntu-latest
        environment: ${{ github.event.inputs.target_environment }}
        steps:
            - name: Azure Login
              uses: azure/login@v1
              with:
                  creds: '{"clientId":"${{ env.ARM_CLIENT_ID }}","clientSecret":"${{ env.ARM_CLIENT_SECRET }}","subscriptionId":"${{ env.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ env.ARM_TENANT_ID }}"}'

            - name: Download Components on First VM
              run: |
                  az vm run-command invoke \
                    --command-id RunPowerShellScript \
                    --name "${{ github.event.inputs.web_api_vm_name }}" \
                    --resource-group "${{ github.event.inputs.resource_group }}" \
                    --scripts '
                    # Download and extract WebApi Installer
                    Invoke-WebRequest -Uri "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_apis/packaging/feeds/EdFi@Release/nuget/packages/EdFi.Suite3.Installer.WebApi/versions/${{ github.event.inputs.version }}/content" -OutFile "C:/Temp/EdFi.Suite3.Installer.WebApi.${{ github.event.inputs.version }}.nupkg"
                    Rename-Item -Path "C:/Temp/EdFi.Suite3.Installer.WebApi.${{ github.event.inputs.version }}.nupkg" -NewName "EdFi.Suite3.Installer.WebApi.zip"
                    Expand-Archive -Path "C:/Temp/EdFi.Suite3.Installer.WebApi.zip" -DestinationPath "C:/Temp/EdFi.Suite3.Installer.WebApi" -Force

                    # Download and extract SwaggerUI
                    Invoke-WebRequest -Uri "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_apis/packaging/feeds/EdFi@Release/nuget/packages/EdFi.Suite3.Installer.SwaggerUI/versions/7.2.6/content" -OutFile "C:/Temp/EdFi.Suite3.Installer.SwaggerUI.nupkg"
                    Rename-Item -Path "C:/Temp/EdFi.Suite3.Installer.SwaggerUI.nupkg" -NewName "EdFi.Suite3.Installer.SwaggerUI.zip"
                    Expand-Archive -Path "C:/Temp/EdFi.Suite3.Installer.SwaggerUI.zip" -DestinationPath "C:/Temp/EdFi.Suite3.Installer.SwaggerUI" -Force

                    # Download and extract SandboxAdmin
                    Invoke-WebRequest -Uri "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_apis/packaging/feeds/EdFi@Release/nuget/packages/EdFi.Suite3.Installer.SandboxAdmin/versions/7.2.7/content" -OutFile "C:/Temp/EdFi.Suite3.Installer.SandboxAdmin.nupkg"
                    Rename-Item -Path "C:/Temp/EdFi.Suite3.Installer.SandboxAdmin.nupkg" -NewName "EdFi.Suite3.Installer.SandboxAdmin.zip"
                    Expand-Archive -Path "C:/Temp/EdFi.Suite3.Installer.SandboxAdmin.zip" -DestinationPath "C:/Temp/EdFi.Suite3.Installer.SandboxAdmin" -Force'

            - name: Download RestApi Databases on Second VM
              run: |
                  az vm run-command invoke \
                    --command-id RunPowerShellScript \
                    --name "${{ github.event.inputs.sql_vm_name }}" \
                    --resource-group "${{ github.event.inputs.resource_group }}" \
                    --scripts '
                    # Download and extract RestApi Databases
                    Invoke-WebRequest -Uri "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_apis/packaging/feeds/EdFi@Release/nuget/packages/EdFi.Suite3.RestApi.Databases.Standard.5.1.0/versions/7.2.1201/content" -OutFile "C:/Temp/EdFi.Suite3.RestApi.Databases.Standard.5.1.0.nupkg"
                    Rename-Item -Path "C:/Temp/EdFi.Suite3.RestApi.Databases.Standard.5.1.0.nupkg" -NewName "EdFi.Suite3.RestApi.Databases.Standard.zip"
                    Expand-Archive -Path "C:/Temp/EdFi.Suite3.RestApi.Databases.Standard.zip" -DestinationPath "C:/Temp/EdFi.Suite3.RestApi.Databases.Standard" -Force
                    Remove-Item -Path "C:/Temp/EdFi.Suite3.RestApi.Databases.Standard/configuration.postgreSQL.json" -Force'

            - name: Create Deployment Script
              run: |
                  SCRIPT_CONTENT='
                  Set-Location "C:\Temp\EdFi.Suite3.RestApi.Databases.Standard"

                  Write-Host "Creating ps1 file..."
                  "Import-Module .\Deployment.psm1" | Out-File -FilePath "dbs_installation.ps1"
                  "Initialize-DeploymentEnvironment" | Out-File -FilePath "dbs_installation.ps1" -Append

                  Write-Host "File created successfully"
                  Get-Content -Path "dbs_installation.ps1"'

                  az vm run-command invoke \
                    --command-id RunPowerShellScript \
                    --name "${{ github.event.inputs.sql_vm_name }}" \
                    --resource-group "${{ github.event.inputs.resource_group }}" \
                    --scripts "$SCRIPT_CONTENT"

            - name: Create WebApi Installation Script
              run: |
                  SCRIPT_CONTENT='
                  Set-Location "C:\Temp\EdFi.Suite3.Installer.WebApi"

                  Write-Host "Creating WebApi installation script..."
                  @"
                  Import-Module .\Install-EdFiOdsWebApi.psm1
                  `$parameters = @{
                      PackageVersion = "7.2.1201"
                      PackageName = "EdFi.Suite3.Ods.WebApi.Standard.5.1.0"
                      DbConnectionInfo = @{
                         Engine = "SqlServer"
                         Server = "${{ github.event.inputs.db_server }}"
                         Username = "${{ github.event.inputs.db_username }}"
                         Password = "${{ github.event.inputs.db_password }}"
                         UseIntegratedSecurity = `$false
                      }
                      IsSandbox = `$true
                      UnEncryptedConnection = `$true
                  }
                  Install-EdFiOdsWebApi @parameters
                  "@ | Out-File -FilePath "webapi_installation.ps1"

                  Write-Host "File created successfully"
                  Get-Content -Path "webapi_installation.ps1"'

                  az vm run-command invoke \
                    --command-id RunPowerShellScript \
                    --name "${{ github.event.inputs.web_api_vm_name }}" \
                    --resource-group "${{ github.event.inputs.resource_group }}" \
                    --scripts "$SCRIPT_CONTENT"
