# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Package Pre-Release
on:
  push:
    paths:
      - 'src/**'
      - '!src/**/*.md'
    branches:
      - main
  workflow_dispatch:

env:
  PACKAGE_NAME: Suite_3_Performance_Test_Suite_Package_Pre-Release
  TEST_RUNNER: TestRunner.psm1 # to do: need to be part of the package
  RUN_TEST: run-tests.ps1 # to do: need to be part of the package
  RUN_REPORT: run-report.bat  # to do: need to be part of the package
  DEPLOY: ./eng/deploy.ps1   # to do: need to be part of the package

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
        matrix:
            package:
                - edfi-performance-test
                - edfi-paging-test
                - perf-test-analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b  # v3.0.2

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Python 3.9
        uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6 # v3.1.2
        with:
          python-version: "3.9"
          cache: "poetry"

      - name: Build Performance
        run: |
          # Next line keeps poetry from trying to use the runner's default Python version
          pushd src/${{ matrix.package }} && poetry env use "3.9" && popd
          python ./eng/build.py ci:publish ${{ matrix.package }}

#  package:
#    runs-on: ubuntu-latest

#    needs: build

#    steps:
#      - name: Checkout code
#        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b  # v3.0.2

#      - name: Run package creation
#        run: |
#          cd src
#          python -m pip install --user --upgrade build
#          python -m build

      - name: Upload Suite-3-Performance-Testing
        if: success()
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
        with:
            # name: ${{ env.PACKAGE_NAME }} -$buildCounter
            name: ${{ matrix.package }} -$buildCounter
            path: ${{ github.workspace }}/Suite-3-Performance-Testing/NugetPackages/*.nupkg
